spring:
  application:
    name: smkt-pantry
  data:
    mongodb:
      database: smkt
      uri: mongodb://root:secret@localhost:27017/ 
      

server:
  port: 4070

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true

logging:
  level:
    '[com.antonioalejandro.smkt.pantry]': DEBUG

id_files_instance: smkt-files
id_oauth_instance: smkt-oauth
