spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  application:
    name: smkt-pantry

server:
  port: 4070

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetchRegistry: true

logging:
  level:
    '[com.antonioalejandro]': DEBUG

mongodb:
  connection: mongodb://root:secret@localhost:27017/
  database:
    name: smkt_pantry
    collection: products

id_files_instance: smkt-files
id_oauth_instance: smkt-oauth
